<?php
if(isset($_POST['submit_email']) && $_POST['email'])
{
  include 'conn.php';
  $email=$_POST['email'];
  
  $select="select * from users where email='$email'";
  $row1 = $conn->query($select);

  if ($row1->num_rows == 1)
  {
    $row=mysqli_fetch_array($row1);
    
    $email=$row['email'];
    $pass=md5($row['password']);
    

    $link="<a href='http://localhost/agrifarm/reset_pass.php?key=".$email."&reset=".$pass."'>Click To Reset password</a>";

    //uncomment below line if you host your website and change the address until reset_pass following your domain and also comment above line for localhost
    //$link="<a href='https://demo.neuon.ai/agrifarm/reset_pass.php?key=".$email."&reset=".$pass."'>Click To Reset password</a>";
    require 'PHPMailer/PHPMailerAutoload.php';
    $mail = new PHPMailer();
    $mail->isSMTP();                                 // Set mailer to use SMTP
      $mail->Host = 'smtp.gmail.com';                 // Specify main and backup SMTP servers
      $mail->SMTPAuth = true;                        // Enable SMTP authentication
      $mail->Username = '';    // SMTP username
      $mail->Password = '';           // SMTP password
      $mail->SMTPSecure = 'tls';                   // Enable TLS encryption, `ssl` also accepted
      $mail->Port = 587;                           // TCP port to connect to

      $mail->setFrom("", "Reset Password");
      $mail->addAddress($email);   // Add a recipient
      
      $mail->isHTML(true);  // Set email format to HTML

    $mail->Subject  =  'Reset Password';
    $mail->Body    = 'Dear Sir/Madam,<br><br>Please use the following link to reset/change your password<br><br>Link: '.$link.'
    
    <br><br>--<br>This is an autogenerated email. Please do not reply to this email directly.';
    if($mail->Send())
    {
      echo "<script>alert('Check Your Email and Click on the link sent to your email to reset your password');</script>";
    }
    else
    {
        echo "<script>alert('Mail Error - > SMTP CONNECT() FAILED.');</script>";
    }
  }	
  
  else {
      echo "<script>alert('This Email is not registered..!');</script>";
  }
  
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title></title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <!-- Main css -->
    <link rel="stylesheet" href="css/custom.css">
</head>
<!-- Navbar-->
<header class="header">
    <nav class="navbar navbar-expand-lg navbar-light py-3" style="box-shadow: inset 1px 1px 0 rgba(0,0,0,.1), inset 0 -1px 0 rgba(0,0,0,.07); ">
        <div class="container">
            <!-- Navbar Brand -->
            <a href="index.php" class="navbar-brand" style="padding: 0;">
                <img src="images/logo.png" alt="logo" width="50px" height="50px">
                <h3 class="display-4" style="line-height: 5px;font-size: 18px; font-style: italic; ">Daily Agri Farm</h3>
            </a>
        </div>
    </nav>
</header>


<body>
<section class="container">
	<br>
	<section class="row justify-content-center">
    <form method="post">
      <h4><br>Enter Email Address To Send Password Link</h4><br>
      <div class="form-group">
        <input style="font-size: 14px;" type="email" class="form-control" name="email" placeholder="Type your Email" required="required">
      </div>
      <div class="form-group">
        <input type="submit" name="submit_email" class="btn btn-primary btn-block btn-lg">
      </div>
    </form>
	</section>

</section>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</body>
</html>
